services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_example
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_ROOT_HOST: "%"
    # mem_limit: 1024m
    # command: >
    #   --innodb-buffer-pool-size=128M
    #   --innodb-log-buffer-size=32M
    #   --max-connections=50
    #   --performance-schema=OFF
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_example
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "0.0.0.0:8080:80"
    depends_on:
      - mysql
    networks:
      - appnet


networks:
  appnet:
    driver: bridge